name: fov_fall2024_waiter_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  convex_bottom_bar: ^3.2.0
  cron: ^0.6.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_analog_clock: ^1.0.3
  flutter_local_notifications: ^17.2.3
  flutter_secure_storage: ^9.2.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^8.0.2
  http: ^1.2.2
  intl: ^0.19.0
  material: ^1.0.0+2
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  redis: ^4.0.0
  shared_preferences: ^2.3.3
  signalr_netcore: ^1.4.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
